### ISSUE TITLE
Monorepo Enhancements

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#235]
## Todo
- [x] Discuss `npm` scripts (e.g. build, lint, test, circle, watch, dev etc.)
- [x] Testing (in consumer projects)
- [x] Final Checks
    - [x] Add information on the project history (`--follow`) etc 

## Context
Toolkit 2.0 progression
